// Import necessary dependencies and types
import type { Metadata } from "next"; // For defining page metadata
import localFont from "next/font/local"; // For loading local fonts
import "./globals.css"; // Global styles
import { Navbar } from "./components/NavBar"; // Navigation component
import Footer from "./components/Footer"; // Footer component
import { LoadingProvider } from "./components/LoadingProvider";
import { Toaster } from "sonner";

// Configure Geist Sans font with variable font weights
const geistSans = localFont({
  src: "./fonts/GeistVF.woff", // Path to font file
  variable: "--font-geist-sans", // CSS variable name
  weight: "100 900", // Supported font weights
});

// Configure Geist Mono font with variable font weights
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff", // Path to font file
  variable: "--font-geist-mono", // CSS variable name 
  weight: "100 900", // Supported font weights
});

// Define metadata for the application
export const metadata: Metadata = {
  title: "Create Next App", // Page title shown in browser tab
  description: "Generated by create next app", // Meta description for SEO
};

// RootLayout component that wraps the entire application
export default function RootLayout({
  children, // Child components to be rendered within the layout
}: Readonly<{
  children: React.ReactNode; // Type definition for children prop
}>) {
  return (
    // Root HTML element with Italian language and dark theme
    <html lang="it" className="light">
      {/* Body element with background and text colors from theme */}
      <body
        className={`bg-background text-foreground`}>
        <LoadingProvider>
          <Navbar/> {/* Navigation bar at the top */}
          <Toaster />
          {children} {/* Main content area */}
          <Footer /> {/* Footer at the bottom */}
        </LoadingProvider>
      </body>
    </html>
  );
}
